Add mentions
ONLYOFFICE/document-server-integration pull request #159
Opened 2021-05-17 10:07 UTC by metoou

Add mentions for: csharp-mvc, csharp, java, php, python and ruby projects

2021-05-17 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ONLYOFFICE/document-server-integration?pullRequest=159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ONLYOFFICE/document-server-integration?pullRequest=159) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: aleksanderfedorov<br/>:x: metoou<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ONLYOFFICE/document-server-integration?pullRequest=159) it.</sub>

2021-05-25 13:11 UTC, aleksanderfedorov approved these changes

2021-05-26 07:22 UTC, LinneyS requested changes

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/nodejs/app.js
> +const { getUsersForMentions } = require("./helpers/users");
this line is not required

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/nodejs/views/editor.ejs
> +                        "onRequestSendNotify": onRequestSendNotify,
Do not send this functions for anonymous

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/csharp/DocEditor.aspx.cs
> +        protected string users { get; private set; }
rename to `usersForMentions`

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/java/src/main/java/controllers/EditorServlet.java
> +        List<Map<String, Object>> usersData = !user.id.equals("uid-0") ? Users.getUsersForMentions(user.id) : null;
rename to `usersForMentions`

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/nodejs/views/editor.ejs
> +                        "onRequestSendNotify": onRequestSendNotify,
on all lang change the same

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/php/doceditor.php
> +    $users = $user->id != "uid-0" ? getUsersForMentions($user->id) : null;
rename to `usersForMentions`

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/python/src/views/actions.py
> +    usersData = users.getUsersForMentions(user.id) if user.id !='uid-0' else None
rename to `usersForMentions`

2021-05-26 07:22 UTC, LinneyS commented on web/documentserver-example/python/src/views/actions.py
> +        'users': json.dumps(usersData)
rename to `usersForMentions`

2021-05-31 09:44 UTC, merged