Feature/wopi editing
ONLYOFFICE/document-server-integration pull request #245
Opened 2021-12-30 13:54 UTC by VolshebnikQ

2022-01-10 11:09 UTC, LinneyS requested changes

2022-01-10 11:09 UTC, LinneyS commented on web/documentserver-example/nodejs/helpers/docManager.js
> +    if (wopi){
not used

2022-01-10 11:09 UTC, LinneyS commented on web/documentserver-example/nodejs/helpers/docManager.js
> +        docManager.fileSizeZero(fileName);
duplicate

2022-01-10 11:09 UTC, LinneyS commented on web/documentserver-example/nodejs/helpers/docManager.js
> +    fileSystem.unlinkSync(path);
use in app.js 
`app.delete("/file"`

2022-01-11 12:36 UTC, Eloncase approved these changes

2022-01-14 13:27 UTC, LinneyS requested changes
Delete creation with sample data

Fix `version` in file info

2022-01-17 08:23 UTC, merged