Feature/add upload wopi
ONLYOFFICE/document-server-integration pull request #246
Opened 2021-12-30 15:29 UTC by VolshebnikQ

2022-01-10 10:34 UTC, LinneyS requested changes
```
ConverExtList is not defined
jscript.js:120
```

2022-01-11 12:19 UTC, Eloncase approved these changes

2022-01-11 13:25 UTC, LinneyS requested changes
dragdrop upload?

2022-01-11 13:25 UTC, LinneyS commented on web/documentserver-example/nodejs/views/wopiIndex.ejs
> +        var UrlEditor = "editor";
Not correct for WOPI

2022-01-11 13:25 UTC, LinneyS commented on web/documentserver-example/nodejs/views/wopiIndex.ejs
> +        <div id="beginEmbedded" class="button gray disable">Embedded view</div>
Remove

2022-01-14 12:53 UTC, LinneyS requested changes

2022-01-14 12:53 UTC, LinneyS commented on web/documentserver-example/nodejs/helpers/wopi/wopiRouting.js
> +                editedExts: configServer.get('editedDocs'),
Filter extensions from config that are in discovery for edit action

2022-01-19 14:15 UTC, LinneyS requested changes

2022-01-19 14:15 UTC, LinneyS commented on web/documentserver-example/nodejs/public/javascripts/jscript.js
> +        var checkFilled = FilledExtList.split(",").find(i => i == posExt);
support IE required

2022-01-19 15:07 UTC, merged