ruby: deleting uid cookie
ONLYOFFICE/document-server-integration pull request #311
Opened 2022-11-15 07:58 UTC by VGKurguzov

2022-11-15 08:43 UTC, Eloncase requested changes

2022-11-15 08:43 UTC, Eloncase commented on web/documentserver-example/ruby/app/assets/javascripts/jscript.js
> +    if ("" != userId && undefined != userId)
if (userId)

2022-11-15 08:43 UTC, Eloncase commented on web/documentserver-example/ruby/app/assets/javascripts/jscript.js
> +        if (userId != "" && userId != undefined) {
if (userId)

2022-11-16 08:38 UTC, aleksandrfedorov97 approved these changes

2022-11-28 13:22 UTC, merged