python: pin and add new dependencies
ONLYOFFICE/document-server-integration pull request #403
Opened 2023-06-26 10:11 UTC by vanyauhalin

- python: pin dependency versions
- python: pin python version
- python: add lint dependencies
- python: add help, dev, lint, prod recipes to Makefile

2023-07-03 07:26 UTC, Nsenz approved these changes

2023-07-04 08:08 UTC, LinneyS requested changes

2023-07-04 08:08 UTC, LinneyS commented on web/documentserver-example/python/3rd-Party.license
> +License:        GPL v2
this type of license is not allowed for us

2023-07-05 07:02 UTC, merged

2023-07-05 07:02 UTC, Nsenz approved these changes