Feature/version on front
ONLYOFFICE/document-server-integration pull request #497
Opened 2023-11-29 07:13 UTC by RIN9A

Added version on front page editor

2023-11-29 07:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ONLYOFFICE/document-server-integration?pullRequest=497) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ONLYOFFICE/document-server-integration?pullRequest=497) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ONLYOFFICE/document-server-integration?pullRequest=497) it.</sub>

2023-11-29 12:37 UTC, aleksandrfedorov97 requested changes

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/python/templates/editor.html
> +
need to add a version tag to index.html

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/python/templates/editor.html
> +
empty line

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/ruby/app/views/layouts/application.html.erb
> +
empty line

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/php/templates/docEditor.tpl
> +    <meta name="server-version" content="{serverVersion}">
need to add a version tag to index.tpl

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/java-spring/src/main/resources/templates/editor.html
> +        <meta name="server-version" th:content="${serverVersion}"/>
need to add a version tag to index.html

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/java/src/main/webapp/editor.jsp
> -
line deleted

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/java/src/main/webapp/editor.jsp
> +        <meta name="server-version" content="<%= ConfigManager.getProperty("version") %>" />
need to add a version tag to index.jsp

2023-11-29 12:37 UTC, aleksandrfedorov97 commented on web/documentserver-example/nodejs/views/editor.ejs
> +    <meta name="server-version" content="<%= serverVersion %>">
need to add a version tag to index.ejs

2023-11-30 07:56 UTC, sshakndr requested changes
Put back 2nd line in editor.jsp file.

2023-12-01 07:55 UTC, aleksandrfedorov97 approved these changes

2023-12-01 08:50 UTC, ZEROM22 approved these changes

2023-12-01 11:20 UTC, sshakndr approved these changes

2023-12-05 10:37 UTC, merged