Feature/php forced conversion
ONLYOFFICE/document-server-integration pull request #531
Opened 2024-02-28 09:50 UTC by mwgiorno

When the auto-conversion error(-9) occurs, the user is able to select the preferred output format choosing between document, spreadsheet, or presentation.

2024-02-28 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ONLYOFFICE/document-server-integration?pullRequest=531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ONLYOFFICE/document-server-integration?pullRequest=531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ONLYOFFICE/document-server-integration?pullRequest=531) it.</sub>

2024-02-29 12:12 UTC, aleksandrfedorov97 commented
Need to disable the file type button after selecting.
![image](https://github.com/ONLYOFFICE/document-server-integration/assets/62958171/2bca6d2d-828c-4be0-9b43-4fb1f29f2a58)

2024-02-29 12:24 UTC, aleksandrfedorov97 requested changes

2024-02-29 12:24 UTC, aleksandrfedorov97 commented on web/documentserver-example/php/templates/index.tpl
> +                    <div id="forceConvert" class="button forceConvert document" data="docx">Document</div>
According to the HTML standard, an ID must be unique throughout the document.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

2024-02-29 12:24 UTC, aleksandrfedorov97 commented on web/documentserver-example/php/assets/js/jscript.js
> +                        checkConvert(response.fileUri, filePass, forceConvert);
The meaning of the name "fileType" is more suitable instead of "forceConvert"

2024-02-29 12:24 UTC, aleksandrfedorov97 commented on web/documentserver-example/php/assets/js/jscript.js
> +
empty line

2024-02-29 12:24 UTC, aleksandrfedorov97 commented on web/documentserver-example/php/src/ajax.php
> +    $convExt = $post['fileExt'] ?? $internalExtension;
Where does the 'fileExt' parameter come from?

2024-03-01 08:12 UTC, aleksandrfedorov97 approved these changes

2024-03-01 10:05 UTC, sshakndr approved these changes

2024-03-06 08:50 UTC, rivexe approved these changes

2024-03-07 12:59 UTC, merged