Feature/auto conversion error
ONLYOFFICE/document-server-integration pull request #544
Opened 2024-03-11 12:14 UTC by mwgiorno

Implement a feature for handling auto-conversion output format error (-9)

2024-03-12 10:25 UTC, sshakndr requested changes
when uploading .xml file:
**`ruby`** 

> Upload error: base specified for non string value
> Please select another file and try again.

**`java`** _(tested in docker container, documentserver editor works fine)_ 

> Upload error: Connection refused (Connection refused)
> Please select another file and try again.

2024-03-13 07:43 UTC, aleksandrfedorov97 requested changes

2024-03-13 07:43 UTC, aleksandrfedorov97 commented on web/documentserver-example/java-spring/src/main/java/com/onlyoffice/integration/controllers/FileController.java
> -            e.printStackTrace();
revert e.printStackTrace()

2024-03-13 10:31 UTC, sshakndr commented
also take a look at **`PyLint`**

2024-03-13 13:40 UTC, aleksandrfedorov97 approved these changes

2024-03-19 10:51 UTC, sshakndr approved these changes

2024-03-20 07:02 UTC, merged