Feature/fetching formats
ONLYOFFICE/document-server-integration pull request #551
Opened 2024-03-19 08:21 UTC by mwgiorno

The supported formats are now fetched with ajax request to the backend method. Also added Format and FormatManager classes to facilitate the usage of formats.

2024-03-20 07:57 UTC, sshakndr approved these changes

2024-03-21 06:55 UTC, aleksandrfedorov97 approved these changes

2024-03-21 06:55 UTC, aleksandrfedorov97 commented on web/documentserver-example/java-spring/src/main/java/com/onlyoffice/integration/controllers/FileController.java
> +
move to IndexController

using ResponseEntity model

```
    @GetMapping("/formats")
    @ResponseBody
    public ResponseEntity<List<Format>> formats() {  // return all the supported formats
        return ResponseEntity.ok(formatService.getFormats());
    }
```

2024-03-21 07:21 UTC, aleksandrfedorov97 requested changes
Fix notes on java-spring

2024-03-22 06:10 UTC, aleksandrfedorov97 requested changes

2024-03-22 06:10 UTC, aleksandrfedorov97 commented on web/documentserver-example/java-spring/src/main/java/com/onlyoffice/integration/controllers/IndexController.java
> +        JSONObject result = new JSONObject();
need to add dto object instead of jsonObject

2024-03-27 07:56 UTC, aleksandrfedorov97 approved these changes

2024-04-03 09:31 UTC, merged