Feature/forgotten page
ONLYOFFICE/document-server-integration pull request #561
Opened 2024-04-17 17:02 UTC by mwgiorno

The page fetches and displays all the forgotten files on the document server that belong to the user.

2024-04-18 07:18 UTC, aleksandrfedorov97 approved these changes

2024-04-19 10:59 UTC, LinneyS requested changes

2024-04-19 10:59 UTC, LinneyS commented on web/documentserver-example/php/templates/forgotten.tpl
> +            <a href="">
Insert `./` value

2024-05-14 08:49 UTC, sshakndr approved these changes

2024-05-15 06:45 UTC, aleksandrfedorov97 approved these changes

2024-05-15 09:52 UTC, merged